In [1]:
'''
Numpy最重要的一个特点是其N维数组对象ndarray,它是一系列同类型数据的集合,以0下标为开始进行集合中元素的索引。
ndarray 对象是用于存放同类型元素的多维数组
ndarray 中的每个元素在内存中都有相同存储大小的区域
ndarray 内部由以下内容组成:
    一个指向数据(内存或内存映射文件中的一块数据)的指针
    数据类型或dtype,描述在数组中的固定大小值的格子
    一个表示数组形状(shape)的元祖，表示各维度大小的元祖
Numpy的数组中比较重要的ndarray对象属性有:
    ndarray.ndim   秩，即轴的数量或维度的数量
    ndarray.shape  数组的维度,对于矩阵,n行m列
    ndarray.size   数组元素的总个数,相当于 .shape中的n*m的值
    ndarray.dtype  ndarray对象的元素类型
    ndarray.itemsize  ndarray对象中每个元素的大小，以字节为单位
    ndarray.flags  ndarray对象的内存信息
    ndarray.real   ndarray元素的实部
    ndarray.imag   ndarray元素的虚部
    ndarray.data   包含实际数组元素的缓冲区,由于一般通过数组的索引获取元素,所以通常不需要使用这个属性。
'''

'\nNumpy最重要的一个特点是其N维数组对象ndarray,它是一系列同类型数据的集合,以0下标为开始进行集合中元素的索引。\nndarray 对象是用于存放同类型元素的多维数组\nndarray 中的每个元素在内存中都有相同存储大小的区域\nndarray 内部由以下内容组成:\n    一个指向数据(内存或内存映射文件中的一块数据)的指针\n    数据类型或dtype,描述在数组中的固定大小值的格子\n    一个表示数组形状(shape)的元祖，表示各维度大小的元祖\nNumpy的数组中比较重要的ndarray对象属性有:\n    ndarray.ndim   秩，即轴的数量或维度的数量\n    ndarray.shape  数组的维度,对于矩阵,n行m列\n    ndarray.size   数组元素的总个数,相当于 .shape中的n*m的值\n    ndarray.dtype  ndarray对象的元素类型\n    ndarray.itemsize  ndarray对象中每个元素的大小，以字节为单位\n    ndarray.flags  ndarray对象的内存信息\n    ndarray.real   ndarray元素的实部\n    ndarray.imag   ndarray元素的虚部\n    ndarray.data   包含实际数组元素的缓冲区,由于一般通过数组的索引获取元素,所以通常不需要使用这个属性。\n'

In [2]:
import numpy as np

In [6]:
arr = np.random.randint(10,size=6)
arr

array([6, 3, 7, 2, 2, 3])

In [7]:
arr.ndim

1

In [8]:
arr.shape

(6,)

In [9]:
arr.size

6

In [10]:
arr.dtype

dtype('int64')

In [19]:
'''
ndarray数组除了可以使用底层ndarray构造器来创建外,也可以通过一以下几种方式
    zeros创建指定大小的数组，数组元素以0来填充:
    numpy.zeros(shape,dtype = float,order='C')
'''
x = np.zeros(10)
print(x)
y = np.zeros((3,4))
print(y)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [17]:
x = np.zeros(5,dtype=int)
print(x)

[0 0 0 0 0]


In [22]:
'''
numpy.ones()创建的都是1
'''
x = np.ones(5)
print(x)
x = np.ones((2,3),dtype=int)
print(x)

[1. 1. 1. 1. 1.]
[[1 1 1]
 [1 1 1]]


In [23]:
'''
创建空的数组
numpy.empty(shape,dtype=float,order='C')用来创建一个指定形状(shape),数据类型(dtype)且未初始化的数组，里面的元素的值是之前内存的值

shape:数组的形状
dtype:数据类型:可选
order:有"C"和"F"两个选项，分别代表，行优先河列优先，在计算机内存中的存储元素的顺序。
'''
x = np.empty((2,3))
print(x)

[[1. 1. 1.]
 [1. 1. 1.]]


In [28]:
'''
numpy.linespace(start,stop,num=50,endpoint=True,retstep=False,dtype=None) 用于创建一个一维数组，数组是一个等差数列构成的。
start: 序列的起始值
stop序列的终止值，如果endpoint为true，该值包含于数列中
num要生成的等步长的样本数量，默认为50
endpoint 该值为True时，数列中中包含stop值，反之不包含，默认是True
retstep如果为True时，生成的数组中会显示间距，反之不显示
dtype ndarray的数据类型
'''
np.linspace(0,10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [29]:
np.linspace(0,10,4,endpoint=False)

array([0. , 2.5, 5. , 7.5])

In [30]:
np.linspace(0,10,4,endpoint=False,retstep=True)

(array([0. , 2.5, 5. , 7.5]), 2.5)

In [33]:
'''
logspace()创建等比数组
'''
x = np.logspace(0,9,2)
x

array([1.e+00, 1.e+09])

In [34]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
'''
zeros_like(arr)
结构像哪个数组，但是里面都是0
'''
np.zeros_like(arr)


array([[0, 0, 0],
       [0, 0, 0]])

In [37]:
np.ones_like(arr)

array([[1, 1, 1],
       [1, 1, 1]])