numpy中的random模块包含了很多方法可以用来产生随机数，对random中的一些常用方法:
    seed: 确定随机生成器种子
    permutation: 返回一个序列的随机排列或返回一个随机排列的范围
    shuffle: 对一个序列就地随机排列
    rand: 产生均匀分布的样本值
    randint: 该方法有三个参数low，high，size三个参数。默认high是None，如果只有low，那范围就是[0,low]。如果有high，范围就是[low,high]。
    random(size=None): 该方法返回[0.0,1.0)范围的随机数
    randn(d0,d1,...,dn): randn函数返回一个或一组样本，具有标准正态分布(期望为0，方差为1)。dn表格每个维度，返回值为指定为度的array

In [1]:
import numpy as np

In [2]:
#左闭右开 下面是生成10个
arr = np.random.random(size=10)
print(arr)
arr.shape

[0.65470109 0.74215631 0.83110782 0.29141428 0.45807906 0.52627859
 0.80898526 0.38502128 0.05955466 0.77327038]


(10,)

In [3]:
#三行四列二维数组 也是从[0,1)
arr = np.random.random(size=(3,4))
arr

array([[0.58463563, 0.96336093, 0.3245191 , 0.69559986],
       [0.39755797, 0.0803772 , 0.80397745, 0.58816314],
       [0.92270359, 0.6307837 , 0.19703728, 0.4373026 ]])

In [5]:
#生成5-10的10位一维数组
arr = np.random.randint(5,10,size=10)
arr

array([8, 6, 9, 8, 6, 9, 5, 6, 7, 8])

In [10]:
arr = np.random.randint(5,10,size=10)
arr

array([9, 9, 5, 6, 5, 5, 6, 7, 6, 9])

In [8]:
arr = np.random.randint(5,10,size=(3,4))
arr

array([[7, 6, 6, 9],
       [7, 5, 7, 8],
       [6, 5, 8, 6]])

In [12]:
#randn中最后的n代表normal() 标准正态分布
x = np.random.randn()
x

1.5724247606609127

In [13]:
x = np.random.randn(2,4)
x

array([[-0.6888802 , -0.77021954, -0.81240227,  0.88312577],
       [ 1.8140349 , -0.14983922,  0.15244044,  0.33188505]])

In [14]:
x = np.random.randn(2,3,4)
x

array([[[-0.08985923,  0.48566656, -1.44077337,  0.88369268],
        [ 2.32503965,  1.61654535,  1.0214311 ,  0.91866994],
        [ 0.00329721, -1.52559019,  1.78124651,  0.00718957]],

       [[-0.34859498, -2.23304864,  0.79827294, -2.15913012],
        [ 0.74227796, -1.44132378,  0.34440999, -0.57069801],
        [-0.07724853,  0.59194919,  1.19731429, -1.65755379]]])

In [15]:
#np.random.noraml() 标准正态(高斯分布) 指定方差。 loc:期望 scale:方差 size:形状
print(np.random.normal(loc=3,scale=4,size=(2,2,3)))

[[[ 0.24574041  6.51867218 10.93023471]
  [-4.6391437  -0.49136544  8.49822198]]

 [[ 0.9672063   2.17086964  2.5206908 ]
  [-2.84519708  7.20655656  5.28176173]]]


In [34]:
#seed 确定随机生成器的种子，随机种子是固定的，那么下一个随机分配是固定的
s = np.random.seed(42)

In [35]:
np.random.randn()

0.4967141530112327

In [38]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [39]:
#对一个序列就地随机排序
np.random.shuffle(arr)
arr

array([5, 1, 4, 3, 2])