In [1]:
'''
切片和索引
ndarray对象的内容可以通过索引或切片来访问和修改，与Python中list的切片操作一样。ndarray数组可以基于0-n的下标进行索引，并设置satrt，stop及step参数进行，
从原数组中切割出一个新数组
'''

'\n切片和索引\nndarray对象的内容可以通过索引或切片来访问和修改，与Python中list的切片操作一样。ndarray数组可以基于0-n的下标进行索引，并设置satrt，stop及step参数进行，\n从原数组中切割出一个新数组\n'

In [7]:
import numpy as np

In [39]:
arr = np.arange(12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [40]:
'''
reshape改变数组形状
'''
arr = arr.reshape(4,3)
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [41]:
arr[1]

array([3, 4, 5])

In [42]:
arr[1,2]

5

In [43]:
#前面带遍行，后面代表列 这种方式代表内存地址给temp，那么temp修改了数值那么原来的也会修改
temp = arr[1:3,1:3]
temp

array([[4, 5],
       [7, 8]])

In [35]:
temp[1,1] = 9

In [37]:
temp

array([[4, 5],
       [7, 9]])

In [38]:
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  9],
       [ 9, 10, 11]])

In [46]:
#numpy.copy代表重新复制一份
temp = np.copy(arr[1:3,1:3])

In [47]:
temp[1,1] = 9

In [48]:
temp

array([[4, 5],
       [7, 9]])

In [49]:
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])