numpy中的random模块包含了很多方法可以用来产生随机数，对random中的一些常用方法:
    seed: 确定随机生成器种子
    permutation: 返回一个序列的随机排列或返回一个随机排列的范围
    shuffle: 对一个序列就地随机排列
    rand: 产生均匀分布的样本值
    randint: 该方法有三个参数low，high，size三个参数。默认high是None，如果只有low，那范围就是[0,low]。如果有high，范围就是[low,high]。
    random(size=None): 该方法返回[0.0,1.0)范围的随机数
    randn(d0,d1,...,dn): randn函数返回一个或一组样本，具有标准正态分布(期望为0，方差为1)。dn表格每个维度，返回值为指定为度的array

In [1]:
import numpy as np

In [5]:
arr = np.random.random(size=10)
print(arr)
arr.shape

[0.47739428 0.24032819 0.18247512 0.12457796 0.79989738 0.54829857
 0.93717581 0.85462001 0.67105928 0.1128256 ]


(10,)

In [6]:
arr = np.random.random(size=(3,4))
arr

array([[0.39566311, 0.17012695, 0.92471125, 0.81463141],
       [0.87143419, 0.53372436, 0.88451515, 0.77185884],
       [0.7930425 , 0.28095968, 0.08546511, 0.01363232]])

In [9]:
arr = np.random.randint(10,size=10)
arr

array([0, 4, 9, 2, 3, 4, 2, 6, 7, 2])

In [10]:
arr = np.random.randint(5,10,size=10)
arr

array([9, 9, 5, 6, 5, 5, 6, 7, 6, 9])

In [11]:
arr = np.random.randint(5,10,size=(3,4))
arr

array([[5, 9, 5, 8],
       [9, 6, 9, 8],
       [6, 5, 6, 9]])

In [14]:
x = np.random.randn()
x

0.4760964644357887

In [17]:
x = np.random.randn(2,4)
x

array([[-0.70012098,  0.44383653, -0.79781192,  0.25512385],
       [ 0.53826553,  0.68461125,  1.48326619,  0.33383855]])

In [18]:
x = np.random.randn(2,3,4)
x

array([[[ 0.14757068,  0.40936771,  0.15764812, -1.082334  ],
        [ 0.21768418,  1.50552803, -0.98172113, -1.31659003],
        [ 0.59599783, -0.21261257, -0.45550873,  0.46216689]],

       [[-0.15486602, -1.30050697,  0.31788619, -0.71540444],
        [ 0.04688375,  1.55074676, -0.87846067,  0.45678695],
        [-0.97610983, -1.13149406,  1.94492169, -0.0653399 ]]])

In [36]:
s = np.random.seed(42)

In [37]:
np.random.randn()

0.4967141530112327

In [38]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [44]:
np.random.shuffle(arr)
arr

array([4, 1, 5, 2, 3])