In [1]:
'''
通过reshape方法可以将一维数组变成二维数组，三维数组或者多维数组。
通过ravel方法或者flatten方法可以将多维数组变成一维数字。改变数组的维度还可以直接设置Numpy数组的维度，通过resize也可以改变数组的维度
'''

'\n通过reshape方法可以将一维数组变成二维数组，三维数组或者多维数组。\n通过ravel方法或者flatten方法可以将多维数组变成一维数字。改变数组的维度还可以直接设置Numpy数组的维度，通过resize也可以改变数组的维度\n'

In [2]:
import numpy as np

In [5]:
arr = np.arange(12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [6]:
arr.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [7]:
arr.reshape(1,3,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [22]:
arr.reshape(2,3,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [24]:
arr.reshape((2,3,2)).reshape((12,))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [37]:
arr = arr.reshape((2,6))
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [38]:
arr = arr.ravel()
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [39]:
arr.reshape((2,3,2))
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [41]:
arr.flatten()
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [43]:
arr = arr.reshape(2,3,2)
arr

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])