In [1]:
'''
numpy.split(ary,indices_or_sections,axis)
arr: 被分割的数组
indices_or_sections: 如果是一个整数，就用该数平均切分，如果是一个数组，为沿轴切分的位置。
axis:沿着哪个维度进行切分，默认为0，横向切分，为1时，纵向切分
'''

'\nnumpy.split(ary,indices_or_sections,axis)\narr: 被分割的数组\nindices_or_sections: 如果是一个整数，就用该数平均切分，如果是一个数组，为沿轴切分的位置。\naxis:沿着哪个维度进行切分，默认为0，横向切分，为1时，纵向切分\n'

In [2]:
import numpy as np

In [3]:
arr = np.arange(12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [5]:
np.split(arr,4)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8]), array([ 9, 10, 11])]

In [26]:
#根据索引号切割
np.split(arr,[3,5])

[array([0, 1, 2]), array([3, 4]), array([ 5,  6,  7,  8,  9, 10, 11])]

In [27]:
a = np.array([[1,2,3],[4,5,6],[11,12,13],[14,15,16]])
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16]])

In [28]:
#2代表切两份 axis代表横着
np.split(a,2,axis=0)

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[11, 12, 13],
        [14, 15, 16]])]

In [29]:
a.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6, 11, 12],
       [13, 14, 15, 16]])

In [32]:
#根据位置分割
np.split(a,[2],axis=1)

[array([[ 1,  2],
        [ 4,  5],
        [11, 12],
        [14, 15]]),
 array([[ 3],
        [ 6],
        [13],
        [16]])]

In [33]:
'''
二维转置
transpose()
'''

'\n二维转置\ntranspose()\n'

In [35]:
a = np.arange(1,13).reshape(2,6)
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [36]:
a.transpose()
print(f'置换后数组{a}')

置换后数组[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [40]:
#多维数组置换
arr = np.arange(1,37).reshape(1,3,3,4)
arr.shape

(1, 3, 3, 4)

In [ ]:
#将1，3，3，4转换为3，3，4，1
np.transpose(arr,[1,2,3,0]).sp