In [1]:
'''
聚合函数列表
    np.sum()   求和
    np.prod()  所有元素相乘
    np.mean()  平均值
    np.std()   标准差
    np.var()   方差
    np.median() 中数
    np.power()  幂运算
    np.sqrt()   开方
    np.min()    最小值
    np.max()    最大值
    np.argmin() 最小值的下标
    np.argmax() 最大值的下标
    np.inf()    无穷大
    np.exp(10)  以e为底的指数
    np.log(10)  对数
'''

'\n聚合函数列表\n    np.sum()   求和\n    np.prod()  所有元素相乘\n    np.mean()  平均值\n    np.std()   标准差\n    np.var()   方差\n    np.median() 中数\n    np.power()  幂运算\n    np.sqrt()   开方\n    np.min()    最小值\n    np.max()    最大值\n    np.argmin() 最小值的下标\n    np.argmax() 最大值的下标\n    np.inf()    无穷大\n    np.exp(10)  以e为底的指数\n    np.log(10)  对数\n'

In [2]:
import numpy as np

In [5]:
temp = np.array([1,2,3,5,5])
temp

array([1, 2, 3, 5, 5])

In [6]:
np.sum(temp)

16

In [7]:
np.prod(temp)

150

In [8]:
np.mean(temp)

3.2

In [9]:
np.var(temp)

2.56

In [10]:
np.std(temp)

1.6

In [11]:
np.median(temp)

3.0

In [13]:
np.power(temp,2)

array([ 1,  4,  9, 25, 25])

In [14]:
np.sqrt(temp)

array([1.        , 1.41421356, 1.73205081, 2.23606798, 2.23606798])

In [15]:
np.min(temp)

1

In [16]:
np.max(temp)

5

In [17]:
np.argmin(temp)

0

In [18]:
np.argmax(temp)

3

In [19]:
np.exp(temp)

array([  2.71828183,   7.3890561 ,  20.08553692, 148.4131591 ,
       148.4131591 ])

In [20]:
np.exp(10)

22026.465794806718

In [22]:
np.log(10)

2.302585092994046